# Generated by Django 4.2.2 on 2023-06-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'admin'), ('PROFESSOR', 'professor'), ('STUDENT', 'student')], max_length=32),
        ),
    ]
